CREATE TABLE IF NOT EXISTS "user" (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  session VARCHAR(50) NOT NULL,
  last_visit_at TIMESTAMPTZ
);

ALTER TABLE "user" ALTER COLUMN session DROP NOT NULL;

